spring:
  datasource:
#    url: jdbc:mysql://192.168.1.193:3306/apollo_mini?useUnicode=true&characterEncoding=UTF-8
#    username: apollo_mini
#    password: apollo_mini
    url: jdbc:mysql://10.0.40.107:3306/apollo_mini?useUnicode=true&characterEncoding=UTF-8
    username: apollo_mini
    password: Hmsn2Lwi6xpws8fs
    driver-class-name: com.mysql.jdbc.Driver
    # Hikari 连接池配置
    hikari:
      # 连接池最大连接数，默认是10
      maximum-pool-size: 40
  jpa:
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update