spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apollo_mini?useUnicode=true&characterEncoding=UTF-8
    username: apollo_mini
    password: apollo_mini
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop