spring:
  datasource:
    url: jdbc:mysql://10.0.33.14:53306/apollo_mini?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3306/apollo_mini?useUnicode=true&characterEncoding=UTF-8
    username: apollo_mini
    password: apollo_mini
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update