spring:
  datasource:
#    url: jdbc:mysql://10.0.33.14:53306/apollo_mini?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/apollo_mini?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: fcfc20050545
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: create
